export const apiV1 = {
  healthLive: "/api/v1/health/live",
  healthReady: "/api/v1/health/ready",
  sessions: "/api/v1/sessions",
  session: (id: string) => `/api/v1/sessions/${id}`,
  sessionMessages: (id: string) => `/api/v1/sessions/${id}/messages`,
  sessionSummary: (id: string) => `/api/v1/sessions/${id}/summary`,
  sessionClose: (id: string) => `/api/v1/sessions/${id}/close`,
  severityEvaluate: "/api/v1/severity/evaluate",
  records: "/api/v1/records",
  recordConsent: "/api/v1/records/consent",
  record: (id: string) => `/api/v1/records/${id}`,
  recordEntries: (id: string) => `/api/v1/records/${id}/entries`,
  recordScores: (id: string) => `/api/v1/records/${id}/scores`,
  recordPersist: (id: string) => `/api/v1/records/${id}/persist`,
  recordExport: (id: string) => `/api/v1/records/${id}/export`,
  recordExportJob: (jobId: string) => `/api/v1/records/exports/${jobId}`,
  locationSearch: "/api/v1/location/search",
  providersSearch: "/api/v1/providers/search",
  profileFollowups: "/api/v1/profile/followups",
  voiceCallback: "/api/v1/voice/callback",
  voiceCallbackCancel: "/api/v1/voice/callback/cancel",
  voiceStatus: "/api/v1/voice/status",
  voiceSessions: "/api/v1/voice/sessions",
  voiceSession: (id: string) => `/api/v1/voice/sessions/${id}`,
  voiceDisclosure: "/api/v1/voice/disclosure",
  voiceDisclosureAck: "/api/v1/voice/disclosure/ack",
  voiceToolSubmit: "/api/v1/voice/tools/submit_patient_answer",
  voiceToolNextQuestion: "/api/v1/voice/tools/get_next_question",
  voiceToolSafety: "/api/v1/voice/tools/evaluate_safety",
  voiceToolSummary: "/api/v1/voice/tools/get_factual_summary",
  voiceToolClose: "/api/v1/voice/tools/close_session",
  voiceTelephonyStatus: "/api/v1/voice/telephony/status",
  voiceSummarySms: "/api/v1/voice/summary-sms",
} as const;

export const apiModules = [
  "health",
  "sessions",
  "conversation",
  "summary",
  "records",
  "scores",
  "severity",
  "profiles",
  "providers",
  "location",
  "integrations",
  "whatsapp",
  "ussd",
  "voice",
  "mcp-internal",
] as const;
