export const apiV1 = {
  healthLive: "/api/v1/health/live",
  healthReady: "/api/v1/health/ready",
  sessions: "/api/v1/sessions",
  session: (id: string) => `/api/v1/sessions/${id}`,
  sessionMessages: (id: string) => `/api/v1/sessions/${id}/messages`,
  sessionSummary: (id: string) => `/api/v1/sessions/${id}/summary`,
  sessionClose: (id: string) => `/api/v1/sessions/${id}/close`,
  severityEvaluate: "/api/v1/severity/evaluate",
  records: "/api/v1/records",
  recordEntries: (id: string) => `/api/v1/records/${id}/entries`,
  recordScores: (id: string) => `/api/v1/records/${id}/scores`,
  recordExport: (id: string) => `/api/v1/records/${id}/export`,
  locationSearch: "/api/v1/location/search",
  providersSearch: "/api/v1/providers/search",
  profileFollowups: "/api/v1/profile/followups",
  voiceCallback: "/api/v1/voice/callback",
  /** Baileys gateway -> API. HMAC-signed, not a public webhook. */
  whatsappInbound: "/api/v1/integrations/whatsapp/inbound",
  whatsappStatus: "/api/v1/integrations/whatsapp/status",
  whatsappOutbox: "/api/v1/integrations/whatsapp/outbox",
  whatsappHealth: "/api/v1/integrations/whatsapp/health",
  /** USSD aggregator callback. */
  ussdCallback: "/api/v1/integrations/ussd",
} as const;

export const apiModules = [
  "health",
  "sessions",
  "conversation",
  "summary",
  "records",
  "scores",
  "severity",
  "profiles",
  "providers",
  "location",
  "integrations",
  "whatsapp",
  "ussd",
  "voice",
  "mcp-internal",
] as const;
